---
- name: Deploy Kubernetes Application
  hosts: k8s  # This must match the group name we will create in the inventory file later
  gather_facts: yes

  tasks:
    - name: Copy deployment.yaml to Kubernetes master
      copy:
        # Use the {{ workspace }} variable so the path is always correct
        src: "{{ workspace }}/deployment.yaml"
        dest: /home/ubuntu/deployment.yaml
      become: yes

    - name: Apply Deployment
      command: kubectl apply -f /home/ubuntu/deployment.yaml
